import type { Locale } from '$lib/types';
import { currentCourse } from '$lib/app';

export const alphabet = currentCourse.glyphs.map(({ answer }) => answer);

export const curricula: Record<Locale, string[]> = {
	en: 'etaoinshrdlucmfwygpbvqxjkz'.split(''),
	de: 'enisratdhulcgmobwfkzpvjyxq'.split(''),
};

export const practiceContent: Record<Locale, { words: string[]; sentences: string[] }> = {
	en: {
		words: [
			'eta',
			'eat',
			'tea',
			'teat',
			'oat',
			'tattoo',
			'toe',
			'iota',
			'tie',
			'anoint',
			'innate',
			'intone',
			'none',
			'note',
			'taint',
			'tenant',
			'titan',
			'noise',
			'onset',
			'saint',
			'sane',
			'sea',
			'stain',
			'stasis',
			'stone',
			'tension',
			'ash',
			'ashen',
			'hiss',
			'shone',
			'theta',
			'thanatos',
			'arise',
			'ear',
			'earth',
			'hear',
			'heart',
			'rain',
			'shrine',
			'star',
			'terror',
			'throne',
			'dead',
			'death',
			'dread',
			'hidden',
			'ordeal',
			'road',
			'tide',
			'alien',
			'altar',
			'hall',
			'lair',
			'lie',
			'tale',
			'aberrant',
			'abyss',
			'acolyte',
			'aeonian',
			'alchemist',
			'ancient',
			'ancestral',
			'antiquary',
			'antiquity',
			'apparition',
			'arcane',
			'archive',
			'astral',
			'awaken',
			'azathoth',
			'basalt',
			'batrachian',
			'beacon',
			'beneath',
			'beyond',
			'bleak',
			'blasphemy',
			'bloodless',
			'burial',
			'catacomb',
			'cavern',
			'celestial',
			'ceremony',
			'cipher',
			'coastline',
			'cosmic',
			'cthulhu',
			'cryptic',
			'cursed',
			'cultist',
			'cyclopean',
			'daemon',
			'dagon',
			'darkness',
			'decay',
			'deepone',
			'delirium',
			'desolate',
			'depths',
			'dimension',
			'distant',
			'dreamer',
			'drowned',
			'eerie',
			'elder',
			'eldritch',
			'entity',
			'esoteric',
			'ethereal',
			'exile',
			'extinct',
			'fathom',
			'fevered',
			'foetid',
			'forbidden',
			'forsaken',
			'forgotten',
			'fossil',
			'frozen',
			'fungal',
			'ghastly',
			'gibbering',
			'gibbous',
			'gloomy',
			'glyph',
			'grimoire',
			'grotesque',
			'haunted',
			'hexagon',
			'hideous',
			'hollow',
			'horizon',
			'horror',
			'howling',
			'ichorous',
			'infernal',
			'innsmouth',
			'insane',
			'ivory',
			'jagged',
			'jester',
			'journal',
			'journey',
			'knowledge',
			'labyrinth',
			'latent',
			'leviathan',
			'lurking',
			'lunar',
			'lunacy',
			'madness',
			'marshes',
			'midnight',
			'miskatonic',
			'monolith',
			'morbid',
			'mutation',
			'nameless',
			'necrotic',
			'necromancy',
			'nexus',
			'nightmare',
			'nocturnal',
			'noisome',
			'obsidian',
			'oceanic',
			'occult',
			'ominous',
			'oracle',
			'outcast',
			'peculiar',
			'petrified',
			'phantom',
			'plague',
			'portal',
			'primeval',
			'quarry',
			'quartz',
			'quest',
			'quiver',
			'relic',
			'reverie',
			'ritual',
			'ruined',
			'rlyeh',
			'sacrilege',
			'sanity',
			'secret',
			'sepulchre',
			'shadow',
			'shoggoth',
			'shunned',
			'silent',
			'sorcery',
			'spectral',
			'squamous',
			'sunken',
			'talisman',
			'temple',
			'tentacle',
			'threshold',
			'tremor',
			'twisted',
			'unearth',
			'unknown',
			'unnatural',
			'unseen',
			'unholy',
			'vault',
			'vessel',
			'vision',
			'voidborn',
			'waking',
			'watcher',
			'waxen',
			'whisper',
			'witchcraft',
			'witches',
			'wraith',
			'xenolith',
			'yellow',
			'yogsothoth',
			'yonder',
			'zealot',
			'zenith',
		],
		sentences: [
			'the bell tolls',
			'fog hides the road',
			'keep the lantern lit',
			'do not look back',
			'footsteps follow us',
			'the door is sealed',
			'something waits outside',
			'stars fade at dawn',
			'the ritual begins',
			'no one answers',
			'the walls are breathing',
			'follow the red moon',
			'we are not alone',
			'the tide is rising',
			'leave before midnight',
			'the candles went dark',
			'a raven keeps watch',
			'silence fills the crypt',
			'trust no shadow',
			'the stone is warm',
			'the old ones awaken',
			'shadows gather at the gate',
			'read the signs in silence',
			'the moon reveals the path',
			'a whisper crosses the void',
			'knowledge sleeps below',
			'from the depths a thousand stars',
			'house of the dreamer',
			'familiar distance',
			'the eternal task remains with the order',
			'the order protects those from persecution',
			'society condemned them as insane',
			'it is not dead which lies eternally',
			'and with strange aeons even death may die',
		],
	},
	de: {
		words: [
			'nein',
			'nie',
			'eis',
			'sinn',
			'sinne',
			'irre',
			'irren',
			'reise',
			'riesen',
			'riss',
			'sirene',
			'aas',
			'eisen',
			'narre',
			'nase',
			'rasen',
			'starre',
			'stein',
			'stern',
			'stirn',
			'tier',
			'tritt',
			'ader',
			'dasein',
			'dienen',
			'drei',
			'eid',
			'ende',
			'reden',
			'sand',
			'ahnen',
			'hand',
			'heiden',
			'hirn',
			'nahen',
			'sehen',
			'stehen',
			'duester',
			'dunst',
			'haus',
			'haut',
			'ruhe',
			'untier',
			'urne',
			'halle',
			'leiden',
			'leise',
			'lesen',
			'seele',
			'still',
			'stille',
			'unheil',
			'urteil',
			'leiche',
			'licht',
			'nicht',
			'schrei',
			'sichel',
			'sicht',
			'abgrund',
			'abseits',
			'abartig',
			'ahnung',
			'ahnenkult',
			'akolyth',
			'albtraum',
			'alchemist',
			'altertum',
			'angst',
			'ankunft',
			'archiv',
			'arkan',
			'astral',
			'atemlos',
			'antiquar',
			'antiquitaet',
			'ausgeburt',
			'azathoth',
			'basalt',
			'beben',
			'bedrohung',
			'bleich',
			'blasphemie',
			'blutleer',
			'brunnen',
			'bucklig',
			'cthulhu',
			'daemon',
			'dagon',
			'daemmerung',
			'dunkel',
			'dunkelheit',
			'duesternis',
			'ekelhaft',
			'einsam',
			'eisern',
			'entfernt',
			'entsetzen',
			'esoterisch',
			'erwachen',
			'erstarrt',
			'ewigkeit',
			'exhumiert',
			'exzentrisch',
			'fackel',
			'faulig',
			'fiebrig',
			'finster',
			'fixiert',
			'fluestern',
			'fremdartig',
			'froschartig',
			'furcht',
			'geheimnis',
			'geister',
			'gezeichnet',
			'gespenst',
			'gewoelbe',
			'grabmal',
			'graesslich',
			'grauen',
			'graeuel',
			'grausig',
			'gruft',
			'grotesk',
			'heimsuchung',
			'heulen',
			'hexenkunst',
			'hoehle',
			'horizont',
			'ichor',
			'infernal',
			'innsmouth',
			'irrlicht',
			'jagend',
			'jenseitig',
			'jenseits',
			'journal',
			'kaelte',
			'katakombe',
			'knochen',
			'kosmosbrut',
			'kosmisch',
			'krypta',
			'kultbuch',
			'kultdiener',
			'kultist',
			'labyrinth',
			'lautlos',
			'leerenbrut',
			'leblos',
			'leere',
			'leviathan',
			'lunatik',
			'maritim',
			'modrig',
			'miskatonic',
			'mondlicht',
			'mondlos',
			'monolith',
			'morast',
			'myriaden',
			'mysterium',
			'mystisch',
			'mutation',
			'nacht',
			'nachtmahr',
			'nachtwache',
			'namenlos',
			'nebel',
			'nekromantie',
			'nexus',
			'obsidian',
			'okkult',
			'phantom',
			'pestilenz',
			'pforte',
			'portal',
			'qualle',
			'qualm',
			'quarz',
			'quelle',
			'quieken',
			'raunen',
			'reflex',
			'relikt',
			'rhythmus',
			'ritual',
			'rlyeh',
			'ruinen',
			'sakrileg',
			'sarkophag',
			'schatten',
			'schaurig',
			'schicksal',
			'schleier',
			'schrecken',
			'schuppig',
			'schwarz',
			'schweigen',
			'seltsam',
			'shoggoth',
			'spektral',
			'sternenkult',
			'sternenlos',
			'sternbild',
			'stollen',
			'sturm',
			'symbol',
			'talisman',
			'tempel',
			'tentakel',
			'tiefen',
			'tiefenwesen',
			'totenkult',
			'toxine',
			'toxisch',
			'traeumer',
			'traumlos',
			'unheilig',
			'uralt',
			'urwesen',
			'verdammt',
			'verboten',
			'verborgen',
			'verflucht',
			'verloren',
			'versunken',
			'verwunschen',
			'verzerrt',
			'vernunft',
			'vision',
			'vorahnung',
			'wahnsinn',
			'wandelnd',
			'wesen',
			'wimmern',
			'xenolith',
			'ypsilon',
			'yogsothoth',
			'zeichen',
			'zerfall',
			'zischen',
			'zornig',
			'zwischen',
			'zyklisch',
			'zyklop',
		],
		sentences: [
			'die glocke schlaegt',
			'nebel verbirgt den weg',
			'halte die laterne an',
			'blick nicht zurueck',
			'schritte folgen uns',
			'die tuer ist versiegelt',
			'etwas wartet draussen',
			'sterne verblassen im morgenrot',
			'das ritual beginnt',
			'niemand antwortet',
			'die waende atmen',
			'folge dem roten mond',
			'wir sind nicht allein',
			'die flut steigt',
			'geh vor mitternacht',
			'die kerzen erloschen',
			'ein rabe haelt wache',
			'stille fuellt die gruft',
			'trau keinem schatten',
			'der stein ist warm',
			'die alten wesen erwachen',
			'schatten sammeln sich am tor',
			'lies die zeichen in der stille',
			'der mond zeigt den pfad',
			'ein fluestern kreuzt die leere',
			'wissen ruht in der tiefe',
			'aus der tiefe tausend sterne',
			'haus des traeumers',
			'traute ferne',
			'die ewige aufgabe bleibt beim orden',
			'der orden schuetzt sie vor verfolgung',
			'die gesellschaft verurteilte sie als wahnsinnig',
			'es ist nicht tot was ewig liegt',
			'bis dass die zeit den tod besiegt',
		],
	},
};
